- name: Installer Nginx selon le système
  hosts: all
  become: true
  tasks:
    - name: Installer Nginx sur Debian/Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Installer Nginx sur RedHat/CentOS
      yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Installer Nginx sur Fedora
      dnf:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "Fedora"
